dotenv: .env
networks:
  default: development
  rinkeby:
    verify: True
  ropsten:
    verify: True
  goerli:
    verify: True
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}
contract:
  address: ${CONTRACT_ADDRESS}
