from brownie import network, config, accounts
from filehash import FileHash

LOCAL_BLOCKCHAIN_ENVIRONMENTS = ["development", "ganache-local"]

# Retrieves the relevant account depending on the network
def get_account():
    # If working on development chain (eg. Ganache cli)
    if network.show_active() in LOCAL_BLOCKCHAIN_ENVIRONMENTS:
        # Retrieve first account from list of accounts automatically generated by brownie
        return accounts[0]
    else:
        # Retrieve MetaMask private key
        return accounts.add(config["wallets"]["from_key"])


# Generates the sha256 hash for a file
def generate_hash(file):
    hasher = FileHash("sha256")
    file_hash = hasher.hash_file(file)
    return file_hash


def main():
    pass
